### ISSUE TITLE
Missing raytracing.py file 

### ISSUE THREAD

**Issue by thomasnowicki** [acschaefer/polex#2]
Hi Alex,
after trying to run your code on the KITTI dataset, I realized that your "raytracing.py" file is missing in your repository. The function "occupancymap" in the file "mapping.py" requires the underlying code in the "raytracing.py" file. Can you upload the missing part in this repository?

**Comment by acschaefer** [comment]
Hi Thomas,

Thank you for reporting the issues! Please check out my [ray_tracing repository](https://github.com/acschaefer/ray_tracing), where you will find the missing files.

I will include this information in the readme.
